### ISSUE TITLE
AWX Environment Variable Problem.

### ISSUE THREAD

**Issue by skluthe** [xezpeleta/Ansible-Proxmox-inventory#19]
Running into an issue using this script with AWX. Here is where I put the environment variables:

![image](https://user-images.githubusercontent.com/23664304/70400728-33771680-19e1-11ea-8b62-0ae9d00ae67d.png)

Here is the error log:
```
 73.777 INFO     Updating inventory 2: Proxmox
   74.562 INFO     Reading Ansible inventory source: /tmp/awx_12_e1r4rjh_/tmpci65i3mw
   74.576 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
   74.584 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
   74.584 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.0.1.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 158, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1153, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1043, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 214, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 197, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /tmp/awx_12_e1r4rjh_/tmpci65i3mw as it did not pass it's verify_file() method
auto declined parsing /tmp/awx_12_e1r4rjh_/tmpci65i3mw as it did not pass it's verify_file() method
toml declined parsing /tmp/awx_12_e1r4rjh_/tmpci65i3mw as it did not pass it's verify_file() method
 [WARNING]:  * Failed to parse /tmp/awx_12_e1r4rjh_/tmpci65i3mw with script
plugin: Inventory script (/tmp/awx_12_e1r4rjh_/tmpci65i3mw) had an execution
error: Traceback (most recent call last):   File
"/tmp/awx_12_e1r4rjh_/tmpci65i3mw", line 488, in <module>     main()   File
"/tmp/awx_12_e1r4rjh_/tmpci65i3mw", line 473, in main     data =
main_list(options, config_path)   File "/tmp/awx_12_e1r4rjh_/tmpci65i3mw", line
210, in main_list     proxmox_api = ProxmoxAPI(options, config_path)   File
"/tmp/awx_12_e1r4rjh_/tmpci65i3mw", line 122, in __init__     'Missing
mandatory parameter --url (or PROXMOX_URL or "url" key in config file).')
Exception: Missing mandatory parameter --url (or PROXMOX_URL or "url" key in
config file).
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
    raise AnsibleParserError(to_native(e))
 [WARNING]:  * Failed to parse /tmp/awx_12_e1r4rjh_/tmpci65i3mw with yaml
plugin: Syntax Error while loading YAML.   mapping values are not allowed in
this context  The error appears to be in '/tmp/awx_12_e1r4rjh_/tmpci65i3mw':
line 30, column 4, but may be elsewhere in the file depending on the exact
syntax problem.  The offending line appears to be:   try:    ^ here
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/yaml.py", line 105, in parse
    raise AnsibleParserError(e)
 [WARNING]:  * Failed to parse /tmp/awx_12_e1r4rjh_/tmpci65i3mw with ini
plugin: /tmp/awx_12_e1r4rjh_/tmpci65i3mw:28: Expected key=value host variable
assignment, got: urllib
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)
 [WARNING]: Unable to parse /tmp/awx_12_e1r4rjh_/tmpci65i3mw as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.
```

Seems like the script isn't getting the variables. Is there any other info I can provide to help out?

**Comment by davidcastellani** [comment]
@skluthe Hey it looks like you are not using the correct environment variables.

In the reposistories README.MD, under instructions section, it lists the environment variable names to use and example values.

```
PROXMOX_URL=https://10.0.0.1:8006/
PROXMOX_USERNAME=apiuser@pve
PROXMOX_PASSWORD=apiuser1234
PROXMOX_INVALID_CERT=False
```

Try changing your environment variables to use the correct names and then try the sync again. Note the `PROXMOX_USERNAME` variable expects `@pve`  or `@pam` after the username depending on what type of account it is.

**Comment by skluthe** [comment]
This worked for me. Thanks!
