### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by ridgebackdad** [xezpeleta/Ansible-Proxmox-inventory#22]
Running this on Ubuntu 18.04.3 LTS using python 2.7.15 returns this:

ridgebackdad@awx:~/Ansible-Proxmox-inventory$ python /etc/ansible/proxmox.py --list --pretty
Traceback (most recent call last):
  File "/etc/ansible/proxmox.py", line 345, in <module>
    main()
  File "/etc/ansible/proxmox.py", line 330, in main
    data = main_list(options, config_path)
  File "/etc/ansible/proxmox.py", line 209, in main_list
    proxmox_api.auth()
  File "/etc/ansible/proxmox.py", line 144, in auth
    validate_certs=self.options.validate))
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 1390, in open_url
    unredirected_headers=unredirected_headers)
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 1294, in open
    r = urllib_request.urlopen(*urlopen_args)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: authentication failure

Running this under python 3 returns:

Traceback (most recent call last):
  File "/etc/ansible/proxmox.py", line 42, in <module>
    from ansible.module_utils.urls import open_url
ModuleNotFoundError: No module named 'ansible'

**The environment variables are set as follows:** 

ridgebackdad@awx:~/Ansible-Proxmox-inventory$ export |grep PROXMOX
declare -x PROXMOX_INVALID_CERT="False"
declare -x PROXMOX_PASSWORD="M@nyN3wThin6z"
declare -x PROXMOX_URL="https://192.168.10.20:8006/"
declare -x PROXMOX_USERNAME="root@pve"

**Comment by monsieurpouet** [comment]
Hi ! 

Download the last script version please. There was an update the 19 Dec.
Its works for me

**Comment by xezpeleta** [comment]
> declare -x PROXMOX_INVALID_CERT="False"

Do you have a valid SSL certificate?

**Comment by xezpeleta** [comment]
It works for me on the same environment.

Could you try using json file configuration instead the environment variables?

**Comment by ridgebackdad** [comment]
looks like it works now with the new version.  Thank you!
