### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by jackyougit** [xezpeleta/Ansible-Proxmox-inventory#42]
When running the script without the use of the json or sh file, it works fine and returns the list of my proxmox machines.
However, when I use the json file I get the following error:

```
python3 /etc/ansible/homelab/proxmox/proxmox.py --list --pretty
Traceback (most recent call last):
  File "/etc/ansible/homelab/proxmox/proxmox.py", line 447, in <module>
    main()
  File "/etc/ansible/homelab/proxmox/proxmox.py", line 432, in main
    data = main_list(options, config_path)
  File "/etc/ansible/homelab/proxmox/proxmox.py", line 288, in main_list
    proxmox_api.auth()
  File "/etc/ansible/homelab/proxmox/proxmox.py", line 145, in auth
    data = json.load(open_url(request_path, data=request_params,
  File "/usr/lib/python3/dist-packages/ansible/module_utils/urls.py", line 1393, in open_url
    return Request().open(method, url, data=data, headers=headers, use_proxy=use_proxy,
  File "/usr/lib/python3/dist-packages/ansible/module_utils/urls.py", line 1304, in open
    return urllib_request.urlopen(request, None, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: authentication failure
```
Any ideas why this might be?

**Comment by maynero** [comment]
@jackyougit, This might be a dumb question, when you use the json or .sh file, are the credentials correct?
Also, are you using Linux PAM or PVE authentication server? Be sure to use `@pam` instead of `@pve` when using Linux PAM.

**Comment by LordBilbon** [comment]
Hello, i have the same issue, i use a ldap auth, and i use username@domain.com, but i have HTTP Error 401: authentication failure.
Any ideas ? Thanks
